# Generated by Django 5.0.8 on 2025-12-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_emails',
            field=models.BooleanField(default=False, help_text='Если включено, куратор будет получать пересылаемые письма от студентов своей группы', verbose_name='Отправлять письма'),
        ),
    ]
