# Generated by Django 5.2.8 on 2026-06-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID во внешней системе'),
        ),
    ]
