# Generated by Django 5.0.8 on 2025-11-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'courses_course',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'courses_lesson',
                'ordering': ['course', 'position', 'name'],
                'unique_together': {('course', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Код')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'courses_task',
                'ordering': ['lesson', 'position', 'name'],
                'unique_together': {('lesson', 'position')},
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время попытки')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Успешна ли попытка')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Баллы')),
                ('score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Баллы (%)')),
                ('results', models.TextField(blank=True, verbose_name='Подробный результат')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attempts', to='students.student', verbose_name='Студент')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Попытка выполнения задания',
                'verbose_name_plural': 'Попытки выполнения заданий',
                'db_table': 'courses_task_attempt',
                'ordering': ['-datetime', 'student'],
            },
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(verbose_name='Дата завершения')),
                ('completion_attempt', models.PositiveIntegerField(verbose_name='Номер попытки завершения')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_tasks', to='students.student', verbose_name='Студент')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_completions', to='courses.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Задание студента',
                'verbose_name_plural': 'Задания студентов',
                'db_table': 'courses_student_task',
                'ordering': ['-completion_date', 'student'],
                'unique_together': {('student', 'task')},
            },
        ),
    ]
